name: Deploy to GitHub Pages

on:
    push:
        branches: [main]

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: true

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"

            - name: Setup Git
              run: |
                  git config --global user.name "GitHub Actions Bot"
                  git config --global user.email "actions@github.com"

            - name: Install dependencies
              run: |
                  yarn install
                  echo "Node version: $(node -v)"
                  echo "Yarn version: $(yarn -v)"

            - name: Build
              run: |
                  yarn build
                  echo "Build output:"
                  ls -la dist/

            - name: Deploy
              run: |
                  git remote -v
                  yarn deploy
